---
- name: login to maas
  include: api/login.yml
  tags:
    - login

- name: set sshkeys
  include: sshkeys/sshkeys.yml
  tags:
    - sshkeys

- name: set config
  include: maas_config/maas_config.yml
  tags:
    - config

- name: set domains
  include: domains/domains.yml
  tags:
    - domains

- name: set vlans and subnets
  include: subnets/subnets.yml
  tags:
    - subnets

- name: set commissioning scripts
  include: commissioning_script/create_scripts.yml
  tags:
    - commissioning_script

- name: set dhcpsnippets
  include: dhcp_snippets/dhcp_snippets.yml
  tags:
    - snippets

- name: set devices
  include: device/devices.yml
  tags:
    - devices

- name: set machines
  include: machine/machines.yml
  tags:
    - machines

- name: logout to maas
  include: api/logout.yml
  tags:
    - login
