---
- name: Login to MAAS
  include: api/login.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - login

- name: Set SSH keys
  include: sshkeys/sshkeys.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - sshkeys

- name: Set MAAS config
  include: maas_config/maas_config.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - config

- name: Set domains
  include: domains/domains.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - domains

- name: Set VLAN's and subnets
  include: subnets/subnets.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - subnets

- name: Set commissioning scripts
  include: commissioning_script/create_scripts.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - commissioning_script

- name: Set DHCP snippets
  include: dhcp_snippets/dhcp_snippets.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - snippets

- name: Set devices
  include: device/devices.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - devices

- name: Set machines
  include: machine/machines.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - machines

- name: Logout of MAAS
  include: api/logout.yml
  when: "'maas-master' in inventory_hostname"
  tags:
    - login

- name: Configure backup of MAAS
  include: backup/configure_backup.yml
  tags:
    - backup
