---
- name: Add SSH key to MAAS
  command: maas {{ maas_user }} sshkeys create key='{{item}}'
  when: current_sshkeys.stdout | from_json | selectattr('key','equalto', item) | list | length == 0
  tags:
    - sshkeys

