---
- name: MAAS | SSHKEYS | check if ssh-keys are available
  command: maas {{maas_user}} sshkeys read
  changed_when: false
  register: current_sshkeys
  tags:
    - sshkeys

- name: MAAS | SSHKEYS | going over keys
  include: sshkeys/createkey.yml
  with_items: "{{ maas_public_keys }}"
  tags:
    - sshkeys
