- name: MAAS | VLANS | Set some facts (1)
  set_fact:
    description: "{{ item.value.name }}"
    mtu: "{{ item.value.mtu | default(default_mtu) }}"
    subnet: "{{ item.value.subnet }}"
    vlan: "{{ item.key }}"
    fabric: "{{ item.value.maas_fabric | default(default_fabric) }}"
    present: "{{ item.value.present | default(true) }}"
    dhcp: "{{ item.value.dhcp | default(true) }}"
    dns_servers: "{{ item.value.dns_servers | default(default_dns)}}"
    dhcp_iprange_start_offset: "{{ item.value.dhcp_start_offset | default(default_maas_dhcp_start_offset ) }}"
    dhcp_iprange_number_of_addresses: "{{ item.value.dhcp_number_of_addresses | default(default_maas_dhcp_number_of_addresses ) }}"
    gateway: "{{ item.value.gateway | default( item.value.subnet | ipaddr('1') | ipaddr('address')) }}"
    dhcp_primary_controller_id: "{{ item.value.maas_primary_rack_controller_id  | default(default_maas_primary_rack_controller_id) }}"
    dhcp_secondary_controller_id: "{{ item.value.maas_secondary_rack_controller_id  | default(default_maas_secondary_rack_controller_id) }}"

- name: MAAS | VLANS | Set some facts (2)
  set_fact:
    dhcp_iprange_start: "{{ subnet | ipaddr(dhcp_iprange_start_offset | int) | ipaddr('address') }}"
    dhcp_iprange_end: "{{ subnet | ipaddr( dhcp_iprange_start_offset|int + dhcp_iprange_number_of_addresses|int ) | ipaddr('address') }}"

- name: MAAS | VLANS | Check if VLAN {{ vlan }} exists
  command: maas {{ maas_user }} vlan read {{ fabric }} {{ vlan }}
  changed_when: false
  failed_when: maas_vlan.rc != 0 and maas_vlan.rc != 2
  register: maas_vlan

- name: MAAS | VLANS | Make sure VLAN {{ vlan }} exists
  command: maas {{ maas_user }} vlans create {{ fabric }} name=vlan-{{vlan}} vid={{vlan}} mtu={{mtu}}
  when: maas_vlan.rc == 2 #and present
  register: maas_vlan_created

- name: MAAS | VLANS | Set vlan_id fact (try 1)
  set_fact:
    vlan_id: "{{ (maas_vlan.stdout | from_json).id }}"
  when: maas_vlan.rc == 0

- name: MAAS | VLANS | Set vlan_id fact (try 2)
  set_fact:
    vlan_id: "{{ (maas_vlan_created.stdout | from_json).id }}"
  when: maas_vlan.rc == 2

- name: MAAS | VLANS | Set fabric_id fact
  set_fact:
    fabric_id: "{{ (maas_fabrics.stdout | from_json | selectattr ('name','equalto', fabric) | map(attribute='id') | list)[0] }}"

- name: MAAS | VLANS | Check if subnet {{ subnet }} exists
  command: maas {{ maas_user }} subnets read
  changed_when: false
  register: maas_subnet

- name: MAAS | VLANS | Set subnet facts (try 1)
  set_fact:
    subnet_id: "{{ (maas_subnet.stdout | from_json | selectattr('cidr','equalto', subnet)|map(attribute='id')|list)[0] | default('-1') }}"

  # dit gaat nu fout omdat vlan al bestaat, moet check of info klopt.
  # eerst subnet/vlan slopen
  # fix ook peer van packages
- name: MAAS | VLANS | Make sure subnet {{ subnet }} exists
  command: >-
    maas {{ maas_user }}
      subnets create
        description="{{description}}"
        cidr="{{subnet}}"
        vlan={{vlan_id}}
        dns_servers="{{dns_servers}}"
        gateway_ip={{gateway}}
        fabric={{fabric_id}}
  when: subnet_id|int == -1
  register: maas_subnet_created

- name: MAAS | VLANS | Set subnet facts (try 2)
  set_fact:
    subnet_id: "{{ (maas_subnet_created.stdout | from_json ).id }}"
  when: maas_subnet_created.changed

- name: MAAS | VLANS | Check if IP range exists
  command: maas {{ maas_user }} ipranges read
  changed_when: false
  register: maas_iprange

- name: MAAS | VLANS | Get IP range id (try 1)
  set_fact:
    iprange_id: "{{ (maas_iprange.stdout | from_json | selectattr( 'comment','equalto', vlan )| map(attribute='id') | list)[0] | default('-1') }}"

- name: MAAS | VLANS | Make sure IP range exists
  command: >
      maas {{ maas_user }} ipranges create
      type=dynamic
      start_ip={{ dhcp_iprange_start }}
      end_ip={{ dhcp_iprange_end }}
      subnet={{subnet_id}} comment={{vlan}}
  when: iprange_id|int == -1 and dhcp
  register: maas_iprange_created

- name: MAAS | VLANS | Get iprange id (try 2)
  set_fact:
    iprange_id: "{{ (maas_iprange_created.stdout | from_json).id }}"
  when: maas_iprange_created.changed

- name: MAAS | VLANS | Read iprange info
  command: maas {{ maas_user }} iprange read {{ iprange_id }}
  changed_when: false
  register: maas_iprange_info
  when: dhcp

- name: MAAS | VLANS | Check if ipranges are changed
  set_fact:
    maas_dhcp_start_changed: "{{ (maas_iprange_info.stdout | from_json).start_ip != dhcp_iprange_start}}"
    maas_dhcp_end_changed:  "{{(maas_iprange_info.stdout | from_json).end_ip != dhcp_iprange_end }}"
  when: >
    maas_iprange_info.rc is defined
    and maas_iprange_info.rc == 0
    and dhcp

- set_fact:
    maas_dhcp_start_changed: false
    maas_dhcp_end_changed: false
  when: >
    maas_iprange_info.skipped is defined
    and maas_iprange_info.skipped
    and not dhcp

- debug:
    msg: start {{ maas_dhcp_start_changed }} end {{ maas_dhcp_end_changed }}

- name: MAAS | VLANS | Update iprange when range is changed
  command: >
      maas {{ maas_user }} iprange update {{ iprange_id }}
      type=dynamic
      start_ip={{ dhcp_iprange_start }}
      end_ip={{ dhcp_iprange_end }}
      subnet={{subnet_id}} comment={{vlan}}
  when: >
    dhcp and ( maas_dhcp_start_changed or maas_dhcp_end_changed )

- name: MAAS | VLANS | Register dhcp status
  command: maas {{ maas_user }} vlan read {{ fabric }} {{ vlan }}
  changed_when: false
  register: maas_vlan_info
  when: maas_vlan.rc == 0

- name: MAAS | VLANS | Make sure DHCP is enabled (high available)
  command: >
    maas {{ maas_user }} vlan update {{ fabric }} {{ vlan }} dhcp_on=True
    primary_rack={{dhcp_primary_controller_id}}
    secondary_rack={{dhcp_secondary_controller_id}}
  when: >
    not (maas_vlan_info.stdout | from_json).dhcp_on | quote | bool 
    and dhcp
    and dhcp_secondary_controller_id != false

- name: MAAS | VLANS | Make sure DHCP is enabled (single dhcp server)
  command: >
    maas {{ maas_user }} vlan update {{ fabric }} {{ vlan }} dhcp_on=True
    primary_rack={{dhcp_primary_controller_id}}
  when: >
    not (maas_vlan_info.stdout | from_json).dhcp_on | quote | bool 
    and dhcp
    and not dhcp_secondary_controller_id


# some breakdown statement (also all create statements should have 'present')
# 1 disable dhcp maas maas vlan update fabric vid dhcp_on=false
# 2 disable range maas maas iprange delete iprange
# 3 disable subnet maas maas subnet delete subnet_id

  #- name: MAAS | VLANS | make sure dhcp is disabled
  #  command: >
  #    maas {{ maas_user }} vlan update {{ fabric }} {{ vlan }} dhcp_on=False
  #  when: >
  #    maas_vlan.rc == 0
  #    and (((maas_vlan_info.stdout | from_json).dhcp_on | bool and not dhcp) or not present)
  #
  #- name: MAAS | VLANS cleanup iprange
  #  command: maas {{ maas_user }} iprange delete {{ iprange_id }}
  #  when: 
  #
  #- name: MAAS | VLANS | cleanup vlan {{vlan}}
  #  debug:
  #    msg: maas {{ maas_user }} vlan delete {{ fabric }} {{vlan}}
  #  when: maas_vlan.rc == 0 and not present
  #  # ignore errors because subnets might be deleting first
  #  ignore_errors: yes
