---

- name: MAAS | DEVICES | set some facts (1)
  set_fact:
    primary_mac_address: "{{ hostvars[item]['network_interfaces'][0]['mac_address'] }}"
    domain: "{{ hostvars[item]['domain'] | default(default_domain)}}"
    interfaces: "{{ hostvars[item]['network_interfaces'] | default([]) }}"
  tags:
    - devices

- name: MAAS | DEVICES | set some facts (2)
  set_fact:
    secondary_interfaces: "{{ interfaces | rejectattr('mac_address','equalto',primary_mac_address) | list  }}"
  tags:
    - devices

- name: MAAS | DEVICES | check if device exists
  command: maas {{ maas_user }} devices read mac_address={{primary_mac_address}}
  changed_when: false
  register: maas_devices_read
  tags:
    - devices

- name: MAAS | DEVICES | get system_id (try 1)
  set_fact:
    device_system_id: "{{ (maas_devices_read.stdout | from_json )[0].system_id }}"
    device_ip_addresses: "{{ (maas_devices_read.stdout | from_json)[0].ip_addresses }}"
  when: maas_devices_read.stdout | from_json | length > 0
  tags:
    - devices

- name: MAAS | DEVICES | make sure device exists
  command: maas {{ maas_user }} devices create hostname={{item}} domain={{domain}} mac_addresses={{primary_mac_address}}
  when: maas_devices_read.stdout | from_json | length == 0
  register: maas_devices_create
  tags:
    - devices

- name: MAAS | DEVICES | get system_id (try 2)
  set_fact:
    device_system_id: "{{ (maas_devices_create.stdout | from_json ).system_id }}"
    device_ip_addresses: "{{ (maas_devices_create.stdout | from_json).ip_addresses }}"
  when: maas_devices_create.changed
  tags:
    - devices

- name: MAAS | DEVICES | get interface ids
  command: maas {{ maas_user }} interfaces read {{ device_system_id }}
  changed_when: false
  register: device_interfaces
  tags:
    - devices

- name: MAAS | DEVICES | make sure all secondary interfaces exist
  include: device/set_interfaces.yml
  with_items: "{{ secondary_interfaces }}"
  when: secondary_interfaces is defined
  tags:
    - devices

- name: MAAS | DEVICES | get interface ids - update
  command: maas {{ maas_user }} interfaces read {{ device_system_id }}
  changed_when: false
  register: device_interfaces
  tags:
    - devices

- name: MAAS | DEVICES | make sure all ip addresses are set
  include: device/set_ips.yml
  with_items: "{{ interfaces }}"
  when: interfaces is defined
  tags:
    - devices

