---
- name: MAAS | DHCP-SNIPPETS | create global snippet {{item.name}}
  command: maas {{ maas_user }} dhcpsnippets create enabled="true" name={{item.name}} global_snippet="true" value=\"{{ item.snippet }}\"
  when: maas_dhcpsnippets.stdout | from_json | selectattr('name','equalto',item.name) | list | length == 0
  tags:
    - snippets
