---
- name: MAAS | DHCP-SNIPPETS | create subnet snippet {{item.name}}
  command: maas {{ maas_user }} dhcpsnippets create enabled="true" name={{item.name}} subnet={{item.subnet}} value=$DHCP_SNIPPET
  environment:
    DHCP_SNIPPET:  "{{ item.snippet }}"
  when: maas_dhcpsnippets.stdout | from_json | selectattr('name','equalto',item.name) | list | length == 0
  tags:
    - snippets
