---
- name: MAAS | MACHINES | set some interface facts (1)
  set_fact:
    mac_address: "{{ item.mac_address }}"
  tags:
    - machines

- name: MAAS | MACHINES | make sure interface with mac {{ mac_address }} exists
  command: maas {{ maas_user }} interfaces create-physical {{ device_system_id }}  mac_address={{ mac_address }}
  when: machine_interfaces.stdout | from_json | selectattr('mac_address','equalto',mac_address) | list | length == 0
  tags:
    - machines
